name: Ежедневный SMS отчёт

on:
  schedule:
    - cron: '30 13 * * *'   # ~ 8:30 утра по твоему времени (Lima, -05), подкорректируй если нужно
  workflow_dispatch:        # позволяет запускать вручную кнопкой

jobs:
  generate-report:
    runs-on: self-hosted
    steps:


      - name: Запустить скрипт отчёта
        run: python report.py

