name: Ежедневный SMS отчёт

on:
  schedule:
    - cron: '30 13 * * *'   # ~ 8:30 утра по твоему времени (Lima, -05), подкорректируй если нужно
  workflow_dispatch:        # позволяет запускать вручную кнопкой

jobs:
  generate-report:
    runs-on: self-hosted
    steps:
      - name: Скачать репозиторий
        uses: actions/checkout@v4

      - name: Установить нужные библиотеки
        run: py -m pip install requests pandas

      - name: Запустить скрипт отчёта
        run: |
         cmd /c C:\Users\larta\AppData\Local\Programs\Python\Python311\python.exe report.py
